/**
 * EXPORT SERVICE
 * Export reports and data to PDF and Excel formats
 * Uses jsPDF for PDF generation and SheetJS for Excel
 */

class ExportService {
    constructor() {
        this.loadedLibraries = {
            jsPDF: false,
            xlsx: false
        };
    }

    /**
     * Export table data to CSV/Excel
     * @param {Array} data - Array of objects to export
     * @param {String} filename - Output filename
     * @param {String} format - 'csv' or 'xlsx'
     */
    async exportToExcel(data, filename = 'export', format = 'csv') {
        try {
            if (format === 'xlsx') {
                await this.loadLibrary('xlsx', 'https://cdn.sheetjs.com/xlsx-latest/package/dist/xlsx.full.min.js');
            }

            // Convert data to worksheet
            const worksheet = this.arrayToWorksheet(data);

            if (format === 'csv') {
                this.downloadCSV(worksheet, filename);
            } else {
                this.downloadXLSX(worksheet, filename);
            }

            if (typeof errorHandler !== 'undefined') {
                errorHandler.showSuccess('Export Successful', `File downloaded as ${filename}.${format}`);
            }

            return { success: true };
        } catch (error) {
            console.error('Export to Excel failed:', error);
            if (typeof errorHandler !== 'undefined') {
                errorHandler.showError('Export Failed', error.message);
            }
            return { success: false, error: error.message };
        }
    }

    /**
     * Export content to PDF
     * @param {Object} options - PDF export options
     */
    async exportToPDF(options = {}) {
        try {
            // Load jsPDF library if not loaded
            await this.loadLibrary('jsPDF', 'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js');

            const {
                title = 'Report',
                filename = 'document.pdf',
                orientation = 'portrait', // 'portrait' or 'landscape'
                data = [],
                elementId = null, // Export specific HTML element
                includeHeader = true,
                includeFooter = true
            } = options;

            // Robustly check for jsPDF constructor
            let jsPDF = window.jspdf ? window.jspdf.jsPDF : null;
            if (!jsPDF && window.jsPDF) jsPDF = window.jsPDF; // Fallback for some UMD builds

            if (!jsPDF) {
                // Last ditch effort: maybe window.jspdf IS the constructor (older versions)
                if (typeof window.jspdf === 'function') jsPDF = window.jspdf;
                else throw new Error('jsPDF library loaded but constructor not found');
            }
            const doc = new jsPDF({ orientation, unit: 'mm', format: 'a4' });

            let yPosition = 20;

            // Add header
            if (includeHeader) {
                doc.setFontSize(20);
                doc.setFont(undefined, 'bold');
                doc.text(title, 15, yPosition);
                yPosition += 10;

                doc.setFontSize(10);
                doc.setFont(undefined, 'normal');
                doc.setTextColor(100);
                doc.text(`Generated on: ${new Date().toLocaleString()}`, 15, yPosition);
                yPosition += 15;
            }

            // Export specific element
            if (elementId) {
                const element = document.getElementById(elementId);
                if (element) {
                    await this.exportElementToPDF(doc, element, yPosition);
                }
            }

            // Export table data
            else if (data.length > 0) {
                this.exportTableDataToPDF(doc, data, yPosition);
            }

            // Add footer
            if (includeFooter) {
                const pageCount = doc.internal.getNumberOfPages();
                for (let i = 1; i <= pageCount; i++) {
                    doc.setPage(i);
                    doc.setFontSize(8);
                    doc.setTextColor(150);
                    doc.text(
                        `Page ${i} of ${pageCount}`,
                        doc.internal.pageSize.getWidth() / 2,
                        doc.internal.pageSize.getHeight() - 10,
                        { align: 'center' }
                    );
                    doc.text(
                        'Generated by EduPortal ERP',
                        doc.internal.pageSize.getWidth() - 15,
                        doc.internal.pageSize.getHeight() - 10,
                        { align: 'right' }
                    );
                }
            }

            // Download PDF
            doc.save(filename);

            if (typeof errorHandler !== 'undefined') {
                errorHandler.showSuccess('PDF Generated', `File downloaded as ${filename}`);
            }

            return { success: true };
        } catch (error) {
            console.error('Export to PDF failed:', error);
            if (typeof errorHandler !== 'undefined') {
                errorHandler.showError('Export Failed', error.message);
            }
            return { success: false, error: error.message };
        }
    }

    /**
     * Export HTML table to PDF
     */
    exportTableDataToPDF(doc, data, startY) {
        if (data.length === 0) return;

        const headers = Object.keys(data[0]);
        const rows = data.map(row => headers.map(header => row[header] || ''));

        // Use autotable plugin if available
        if (doc.autoTable) {
            doc.autoTable({
                head: [headers],
                body: rows,
                startY: startY,
                theme: 'grid',
                styles: { fontSize: 9 },
                headStyles: { fillColor: [59, 130, 246], fontStyle: 'bold' }
            });
        } else {
            // Manual table rendering
            let yPos = startY;
            const colWidth = (doc.internal.pageSize.getWidth() - 30) / headers.length;

            // Headers
            doc.setFontSize(10);
            doc.setFont(undefined, 'bold');
            doc.setFillColor(59, 130, 246);
            doc.setTextColor(255);

            headers.forEach((header, i) => {
                doc.rect(15 + i * colWidth, yPos, colWidth, 8, 'F');
                doc.text(header, 18 + i * colWidth, yPos + 6);
            });

            yPos += 10;

            // Data rows
            doc.setFont(undefined, 'normal');
            doc.setTextColor(0);

            rows.forEach((row, rowIndex) => {
                if (yPos > doc.internal.pageSize.getHeight() - 30) {
                    doc.addPage();
                    yPos = 20;
                }

                row.forEach((cell, cellIndex) => {
                    doc.text(String(cell).substring(0, 100), 18 + cellIndex * colWidth, yPos + 6);
                });

                yPos += 8;
            });
        }
    }

    /**
     * Export HTML element to PDF (basic text extraction)
     */
    async exportElementToPDF(doc, element, startY) {
        const text = element.innerText;
        const lines = doc.splitTextToSize(text, doc.internal.pageSize.getWidth() - 30);

        doc.setFontSize(10);
        doc.text(lines, 15, startY);
    }

    /**
     * Convert array of objects to worksheet
     */
    arrayToWorksheet(data) {
        if (data.length === 0) return [];

        const headers = Object.keys(data[0]);
        const rows = data.map(row => headers.map(header => row[header] || ''));

        return [headers, ...rows];
    }

    /**
     * Download data as CSV
     */
    downloadCSV(worksheet, filename) {
        const csvContent = worksheet.map(row =>
            row.map(cell => `"${String(cell).replace(/"/g, '""')}"`).join(',')
        ).join('\n');

        this.downloadFile(csvContent, `${filename}.csv`, 'text/csv');
    }

    /**
     * Download data as XLSX (requires SheetJS)
     */
    downloadXLSX(worksheet, filename) {
        if (!window.XLSX) {
            throw new Error('SheetJS library not loaded');
        }

        const ws = window.XLSX.utils.aoa_to_sheet(worksheet);
        const wb = window.XLSX.utils.book_new();
        window.XLSX.utils.book_append_sheet(wb, ws, 'Sheet1');

        window.XLSX.writeFile(wb, `${filename}.xlsx`);
    }

    /**
     * Generic file download
     */
    downloadFile(content, filename, mimeType) {
        const blob = new Blob([content], { type: mimeType });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');

        link.href = url;
        link.download = filename;
        link.click();

        // Cleanup
        setTimeout(() => URL.revokeObjectURL(url), 100);
    }

    /**
     * Load external library dynamically
     */
    async loadLibrary(name, url) {
        if (this.loadedLibraries[name]) return;

        return new Promise((resolve, reject) => {
            const script = document.createElement('script');
            script.src = url;
            script.onload = () => {
                this.loadedLibraries[name] = true;
                resolve();
            };
            script.onerror = () => reject(new Error(`Failed to load ${name} library`));
            document.head.appendChild(script);
        });
    }

    /**
     * Export student report card
     */
    async exportStudentReport(studentData) {
        const data = {
            'Student Name': studentData.name || 'N/A',
            'Class': studentData.class || 'N/A',
            'Roll Number': studentData.rollNumber || 'N/A',
            'Attendance': `${studentData.attendance || 0}%`,
            'Overall Grade': studentData.grade || 'N/A',
            'Rank': studentData.rank || 'N/A'
        };

        // Subjects and marks
        if (studentData.subjects && studentData.subjects.length > 0) {
            studentData.subjects.forEach(subject => {
                data[subject.name] = `${subject.marks || 0}/${subject.totalMarks || 100}`;
            });
        }

        return this.exportToPDF({
            title: `Report Card - ${studentData.name}`,
            filename: `report_card_${studentData.rollNumber || 'student'}.pdf`,
            data: [data],
            includeHeader: true,
            includeFooter: true
        });
    }

    /**
     * Export attendance sheet
     */
    async exportAttendanceSheet(attendanceData, classInfo) {
        const tableData = attendanceData.map(record => ({
            'Date': record.date,
            'Student Name': record.studentName,
            'Roll No': record.rollNumber,
            'Status': record.status,
            'Remarks': record.remarks || '-'
        }));

        return this.exportToExcel(tableData, `attendance_${classInfo}_${new Date().toISOString().split('T')[0]}`, 'xlsx');
    }

    /**
     * Export fee report
     */
    async exportFeeReport(feeData) {
        const tableData = feeData.map(fee => ({
            'Student Name': fee.studentName,
            'Class': fee.class,
            'Fee Type': fee.feeType,
            'Amount': `₹${fee.amount}`,
            'Status': fee.status,
            'Due Date': fee.dueDate,
            'Payment Date': fee.paymentDate || 'Pending'
        }));

        return this.exportToPDF({
            title: 'Fee Collection Report',
            filename: `fee_report_${new Date().toISOString().split('T')[0]}.pdf`,
            data: tableData,
            orientation: 'landscape',
            includeHeader: true,
            includeFooter: true
        });
    }

    /**
     * Print current page
     */
    printPage(title = document.title) {
        document.title = title;
        window.print();
    }

    /**
     * Export chart/graph as image
     */
    async exportChartAsImage(chartId, filename = 'chart.png') {
        try {
            const canvas = document.getElementById(chartId);
            if (!canvas || canvas.tagName !== 'CANVAS') {
                throw new Error('Chart element not found or not a canvas');
            }

            const dataURL = canvas.toDataURL('image/png');
            const link = document.createElement('a');
            link.href = dataURL;
            link.download = filename;
            link.click();

            if (typeof errorHandler !== 'undefined') {
                errorHandler.showSuccess('Export Successful', `Chart saved as ${filename}`);
            }

            return { success: true };
        } catch (error) {
            console.error('Export chart failed:', error);
            if (typeof errorHandler !== 'undefined') {
                errorHandler.showError('Export Failed', error.message);
            }
            return { success: false, error };
        }
    }
}

// Initialize export service
const exportService = new ExportService();

// Export for use in other modules
if (typeof module !== 'undefined' && module.exports) {
    module.exports = ExportService;
}
